name: Mutation Tests

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: Build, run mutation tests, and publish results
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@e4169f1bc1d00ee0cce0bf26f6076d9d25d4dc03 # pin@v1.3.2
      with:
        java-version: 8
    - id: install-packages
      name: Install packages
      run: |
        # Install Graphviz
        sudo apt-get -qq update
        sudo apt-get -q install graphviz
        dot -V

# BUILD AND TEST
    - id: build-test
      name: Build and run mutation tests
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          package \
          org.pitest:pitest-maven:mutationCoverage

# GET TEST RESULTS
    - id: upload-test-results
      name: Upload mutation test results
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # @v3
      with:
        name: mutation-test-results
        path: ./schemacrawler-api/target/pit-reports
