name: Quick Build

on:
  workflow_dispatch:
  push:

permissions: read-all

jobs:
  build:
    name: Quick build
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@61236cb7f3cb8d9329417df8c4f3fe2b4d614b30 # pin@v1.2.1
      with:
        java-version: 8
    - id: install-packages
      name: Install packages
      shell: bash
      run: |
        # Install Graphviz
        sudo apt-get -qq update
        sudo apt-get -q install graphviz
        dot -V

# BUILD AND TEST
    - id: build-test
      name: Build all modules and run tests
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          package
